# theme.toml template for a Hugo theme

name = "Techfabric Theme"
license = "MIT"
description = "A theme used in the techfabric website."
tags = []
features = []
min_version = "0.25.1"

[author]
  name = "Yaroslav Zaklynskyi"
  homepage = "http://techfabric.co"
